//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public int Id { get; set; }
        public Nullable<int> HastaId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public string RandevuSaati { get; set; }
        public Nullable<System.DateTime> RandevuTarihi { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
